// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace LufthansaCodedUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// IzracunajCijenuLeta - Use 'IzracunajCijenuLetaParams' to pass parameters into this method.
        /// </summary>
        public void IzracunajCijenuLeta()
        {
            #region Variable Declarations
            WinEdit uINameEdit = this.UIDebugWindow.UIItemWindow.UILufthansaFormListItem.UINameEdit;
            WinGroup uIPodacioletuGroup = this.UIForm1Window.UIPodacioletuWindow.UIPodacioletuGroup;
            WinComboBox uIDOComboBox = this.UIForm1Window.UIOdComboBoxWindow.UIDOComboBox;
            WinComboBox uIDoComboBoxComboBox = this.UIForm1Window.UIDoComboBoxWindow.UIDoComboBoxComboBox;
            WinEdit uIDistancaTextBoxEdit = this.UIForm1Window.UIDistancaTextBoxWindow.UIDistancaTextBoxEdit;
            WinEdit uITakseTextBoxEdit = this.UIForm1Window.UITakseTextBoxWindow.UITakseTextBoxEdit;
            WinSlider uITrackBar1Slider = this.UIForm1Window.UITrackBar1Window.UITrackBar1Slider;
            WinButton uIIzračunajcijenuletaButton = this.UIForm1Window.UIIzračunajcijenuletaWindow.UIIzračunajcijenuletaButton;
            WinButton uICloseButton = this.UIForm1Window.UIForm1TitleBar.UICloseButton;
            WinEdit uIPrtljagTextBoxEdit = this.UIForm1Window.UIPrtljagTextBoxWindow.UIPrtljagTextBoxEdit;
            #endregion

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit, new Point(52, 12));

            // Click 'Podaci o letu' group
            Mouse.Click(uIPodacioletuGroup, new Point(154, 47));

            // Select 'Sarajevo, BiH' in 'Do:' combo box
            uIDOComboBox.SelectedItem = this.IzracunajCijenuLetaParams.UIDOComboBoxSelectedItem;

            // Select 'Beograd, SRB' in 'doComboBox' combo box
            uIDoComboBoxComboBox.SelectedItem = this.IzracunajCijenuLetaParams.UIDoComboBoxComboBoxSelectedItem;

            // Type '9363' in 'distancaTextBox' text box
            uIDistancaTextBoxEdit.Text = this.IzracunajCijenuLetaParams.UIDistancaTextBoxEditText;

            // Type '{Tab}' in 'distancaTextBox' text box
            Keyboard.SendKeys(uIDistancaTextBoxEdit, this.IzracunajCijenuLetaParams.UIDistancaTextBoxEditSendKeys, ModifierKeys.None);

            // Type '0.125' in 'takseTextBox' text box
            uITakseTextBoxEdit.Text = this.IzracunajCijenuLetaParams.UITakseTextBoxEditText;

            // Set position '1' in 'trackBar1' slider
            uITrackBar1Slider.PositionAsString = this.IzracunajCijenuLetaParams.UITrackBar1SliderPositionAsString;

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(81, 19));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(26, 15));

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit, new Point(79, 9));

            // Select 'Sarajevo, BiH' in 'Do:' combo box
            uIDOComboBox.SelectedItem = this.IzracunajCijenuLetaParams.UIDOComboBoxSelectedItem1;

            // Select 'Beograd, SRB' in 'doComboBox' combo box
            uIDoComboBoxComboBox.SelectedItem = this.IzracunajCijenuLetaParams.UIDoComboBoxComboBoxSelectedItem1;

            // Type '9363' in 'distancaTextBox' text box
            uIDistancaTextBoxEdit.Text = this.IzracunajCijenuLetaParams.UIDistancaTextBoxEditText1;

            // Type '4' in 'prtljagTextBox' text box
            uIPrtljagTextBoxEdit.Text = this.IzracunajCijenuLetaParams.UIPrtljagTextBoxEditText;

            // Type '0.125' in 'takseTextBox' text box
            uITakseTextBoxEdit.Text = this.IzracunajCijenuLetaParams.UITakseTextBoxEditText1;

            // Set position '1' in 'trackBar1' slider
            uITrackBar1Slider.PositionAsString = this.IzracunajCijenuLetaParams.UITrackBar1SliderPositionAsString1;

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(88, 9));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(26, 11));
        }
        
        /// <summary>
        /// RezervisiLet - Use 'RezervisiLetParams' to pass parameters into this method.
        /// </summary>
        public void RezervisiLet()
        {
            #region Variable Declarations
            WinEdit uINameEdit = this.UIDebugWindow.UIItemWindow.UILufthansaFormListItem.UINameEdit;
            WinComboBox uIDOComboBox = this.UIForm1Window.UIOdComboBoxWindow.UIDOComboBox;
            WinComboBox uIDoComboBoxComboBox = this.UIForm1Window.UIDoComboBoxWindow.UIDoComboBoxComboBox;
            WinEdit uIDistancaTextBoxEdit = this.UIForm1Window.UIDistancaTextBoxWindow.UIDistancaTextBoxEdit;
            WinEdit uIPrtljagTextBoxEdit = this.UIForm1Window.UIPrtljagTextBoxWindow.UIPrtljagTextBoxEdit;
            WinEdit uITakseTextBoxEdit = this.UIForm1Window.UITakseTextBoxWindow.UITakseTextBoxEdit;
            WinSlider uITrackBar1Slider = this.UIForm1Window.UITrackBar1Window.UITrackBar1Slider;
            WinButton uIIzračunajcijenuletaButton = this.UIForm1Window.UIIzračunajcijenuletaWindow.UIIzračunajcijenuletaButton;
            WinEdit uIImeTextBoxEdit = this.UIForm1Window.UIImeTextBoxWindow.UIImeTextBoxEdit;
            WinEdit uIPrezimeTextBoxEdit = this.UIForm1Window.UIPrezimeTextBoxWindow.UIPrezimeTextBoxEdit;
            WinEdit uIJMBGTextBoxEdit = this.UIForm1Window.UIJMBGTextBoxWindow.UIJMBGTextBoxEdit;
            WinEdit uITelefonTextBoxEdit = this.UIForm1Window.UITelefonTextBoxWindow.UITelefonTextBoxEdit;
            WinEdit uIKomentarRichTextBoxEdit = this.UIForm1Window.UIKomentarRichTextBoxWindow.UIKomentarRichTextBoxEdit;
            WinButton uIRezervišiletButton = this.UIForm1Window.UIRezervišiletWindow.UIRezervišiletButton;
            WinButton uICloseButton = this.UIForm1Window.UIForm1TitleBar.UICloseButton;
            #endregion

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit, new Point(127, 8));

            // Select 'Sarajevo, BiH' in 'Do:' combo box
            uIDOComboBox.SelectedItem = this.RezervisiLetParams.UIDOComboBoxSelectedItem;

            // Select 'Beograd, SRB' in 'doComboBox' combo box
            uIDoComboBoxComboBox.SelectedItem = this.RezervisiLetParams.UIDoComboBoxComboBoxSelectedItem;

            // Type '9363' in 'distancaTextBox' text box
            uIDistancaTextBoxEdit.Text = this.RezervisiLetParams.UIDistancaTextBoxEditText;

            // Type '4' in 'prtljagTextBox' text box
            uIPrtljagTextBoxEdit.Text = this.RezervisiLetParams.UIPrtljagTextBoxEditText;

            // Type '0.2' in 'takseTextBox' text box
            uITakseTextBoxEdit.Text = this.RezervisiLetParams.UITakseTextBoxEditText;

            // Set position '5' in 'trackBar1' slider
            uITrackBar1Slider.PositionAsString = this.RezervisiLetParams.UITrackBar1SliderPositionAsString;

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(106, 10));

            // Type 'Amela' in 'imeTextBox' text box
            uIImeTextBoxEdit.Text = this.RezervisiLetParams.UIImeTextBoxEditText;

            // Type 'Spica' in 'prezimeTextBox' text box
            uIPrezimeTextBoxEdit.Text = this.RezervisiLetParams.UIPrezimeTextBoxEditText;

            // Type '2901994175003' in 'JMBGTextBox' text box
            uIJMBGTextBoxEdit.Text = this.RezervisiLetParams.UIJMBGTextBoxEditText;

            // Type '+38762-999-999' in 'telefonTextBox' text box
            uITelefonTextBoxEdit.Text = this.RezervisiLetParams.UITelefonTextBoxEditText;

            // Type 'sdfs' in 'komentarRichTextBox' text box
            uIKomentarRichTextBoxEdit.Text = this.RezervisiLetParams.UIKomentarRichTextBoxEditText;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(143, 7));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(32, 18));
        }
        
        /// <summary>
        /// ObrisiLet
        /// </summary>
        public void ObrisiLet()
        {
            #region Variable Declarations
            WinEdit uINameEdit = this.UIDebugWindow.UIItemWindow.UILufthansaFormListItem.UINameEdit;
            WinRowHeader uIItemRowHeader = this.UIForm1Window.UIDataGridView1Window.UIDataGridViewTable.UIRow2Row1.UIItemRowHeader;
            WinButton uIIzbrišiuneseniletButton = this.UIForm1Window.UIIzbrišiuneseniletWindow.UIIzbrišiuneseniletButton;
            WinButton uICloseButton = this.UIForm1Window.UIForm1TitleBar.UICloseButton;
            #endregion

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit, new Point(133, 17));

            // Click row header
            Mouse.Click(uIItemRowHeader, new Point(14, 7));

            // Click 'Izbriši uneseni let' button
            Mouse.Click(uIIzbrišiuneseniletButton, new Point(292, 5));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(29, 19));
        }
        
        /// <summary>
        /// FormaErrors - Use 'FormaErrorsParams' to pass parameters into this method.
        /// </summary>
        public void FormaErrors()
        {
            #region Variable Declarations
            WinEdit uINameEdit = this.UIDebugWindow.UIItemWindow.UILufthansaFormListItem.UINameEdit;
            WinButton uIIzračunajcijenuletaButton = this.UIForm1Window.UIIzračunajcijenuletaWindow.UIIzračunajcijenuletaButton;
            WinEdit uIDistancaTextBoxEdit = this.UIForm1Window.UIDistancaTextBoxWindow.UIDistancaTextBoxEdit;
            WinWindow uIPrtljagTextBoxWindow = this.UIForm1Window.UIPodacioletuGroup.UIPrtljagTextBoxWindow;
            WinEdit uIPrtljagTextBoxEdit = this.UIForm1Window.UIPrtljagTextBoxWindow.UIPrtljagTextBoxEdit;
            WinEdit uITakseTextBoxEdit = this.UIForm1Window.UITakseTextBoxWindow.UITakseTextBoxEdit;
            WinButton uICloseButton = this.UIForm1Window.UIForm1TitleBar.UICloseButton;
            #endregion

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit, new Point(98, 12));

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(130, 17));

            // Type '9363' in 'distancaTextBox' text box
            uIDistancaTextBoxEdit.Text = this.FormaErrorsParams.UIDistancaTextBoxEditText;

            // Click 'prtljagTextBox' window
            Mouse.Click(uIPrtljagTextBoxWindow, new Point(61, 18));

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(159, 18));

            // Type '4' in 'prtljagTextBox' text box
            uIPrtljagTextBoxEdit.Text = this.FormaErrorsParams.UIPrtljagTextBoxEditText;

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(125, 18));

            // Type '0.125' in 'takseTextBox' text box
            uITakseTextBoxEdit.Text = this.FormaErrorsParams.UITakseTextBoxEditText;

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(93, 10));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(41, 18));
        }
        
        /// <summary>
        /// FormaErrorsPosiljaoc - Use 'FormaErrorsPosiljaocParams' to pass parameters into this method.
        /// </summary>
        public void FormaErrorsPosiljaoc()
        {
            #region Variable Declarations
            WinEdit uINameEdit = this.UIDebugWindow.UIItemWindow.UILufthansaFormListItem.UINameEdit;
            WinEdit uIImeTextBoxEdit = this.UIForm1Window.UIImeTextBoxWindow.UIImeTextBoxEdit;
            WinButton uIRezervišiletButton = this.UIForm1Window.UIRezervišiletWindow.UIRezervišiletButton;
            WinWindow uIImeTextBoxWindow = this.UIForm1Window.UILičnipodaciGroup.UIImeTextBoxWindow;
            WinGroup uILičnipodaciGroup = this.UIForm1Window.UILičnipodaciWindow.UILičnipodaciGroup;
            WinEdit uIPrezimeTextBoxEdit = this.UIForm1Window.UIPrezimeTextBoxWindow.UIPrezimeTextBoxEdit;
            WinWindow uIJMBGTextBoxWindow = this.UIForm1Window.UILičnipodaciGroup.UIJMBGTextBoxWindow;
            WinEdit uIJMBGTextBoxEdit = this.UIForm1Window.UIJMBGTextBoxWindow.UIJMBGTextBoxEdit;
            WinEdit uITelefonTextBoxEdit = this.UIForm1Window.UITelefonTextBoxWindow.UITelefonTextBoxEdit;
            WinButton uIQuitButton = this.UIForm1Window1.UIForm1Client.UIQuitButton;
            WinComboBox uIDOComboBox = this.UIForm1Window.UIOdComboBoxWindow.UIDOComboBox;
            WinGroup uIPodacioletuGroup = this.UIForm1Window.UIPodacioletuWindow.UIPodacioletuGroup;
            WinComboBox uIDoComboBoxComboBox = this.UIForm1Window.UIDoComboBoxWindow.UIDoComboBoxComboBox;
            WinEdit uIDistancaTextBoxEdit = this.UIForm1Window.UIDistancaTextBoxWindow.UIDistancaTextBoxEdit;
            WinEdit uITakseTextBoxEdit = this.UIForm1Window.UITakseTextBoxWindow.UITakseTextBoxEdit;
            WinButton uIIzračunajcijenuletaButton = this.UIForm1Window.UIIzračunajcijenuletaWindow.UIIzračunajcijenuletaButton;
            WinWindow uIPrezimeTextBoxWindow = this.UIForm1Window.UILičnipodaciGroup.UIPrezimeTextBoxWindow;
            #endregion

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit, new Point(89, 6));

            // Type 'a' in 'imeTextBox' text box
            uIImeTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UIImeTextBoxEditText;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(149, 18));

            // Click 'imeTextBox' window
            Mouse.Click(uIImeTextBoxWindow, new Point(62, -1));

            // Type 'afd' in 'imeTextBox' text box
            uIImeTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UIImeTextBoxEditText1;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(142, 8));

            // Click 'Lični podaci' group
            Mouse.Click(uILičnipodaciGroup, new Point(142, 64));

            // Type 'a' in 'prezimeTextBox' text box
            uIPrezimeTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UIPrezimeTextBoxEditText;

            // Click 'JMBGTextBox' window
            Mouse.Click(uIJMBGTextBoxWindow, new Point(45, 18));

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(167, 15));

            // Click 'Lični podaci' group
            Mouse.Click(uILičnipodaciGroup, new Point(154, 58));

            // Type 'ad' in 'prezimeTextBox' text box
            uIPrezimeTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UIPrezimeTextBoxEditText1;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(162, 9));

            // Type '2901994176333' in 'JMBGTextBox' text box
            uIJMBGTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UIJMBGTextBoxEditText;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(144, 8));

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(142, 11));

            // Move 'JMBGTextBox' window
            Mouse.StartDragging(uIJMBGTextBoxWindow, new Point(101, 0));
            Mouse.StopDragging(uIJMBGTextBoxWindow, -21, 3);

            // Type '2901994175003' in 'JMBGTextBox' text box
            uIJMBGTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UIJMBGTextBoxEditText1;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(167, 15));

            // Type '+38762-888888' in 'telefonTextBox' text box
            uITelefonTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UITelefonTextBoxEditText;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(136, 16));

            // Type '+38762-888-888' in 'telefonTextBox' text box
            uITelefonTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UITelefonTextBoxEditText1;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(207, 19));

            // Click '&Quit' button
            Mouse.Click(uIQuitButton, new Point(34, 9));

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit, new Point(112, 11));

            // Select 'Sarajevo, BiH' in 'Do:' combo box
            uIDOComboBox.SelectedItem = this.FormaErrorsPosiljaocParams.UIDOComboBoxSelectedItem;

            // Click 'Podaci o letu' group
            Mouse.Click(uIPodacioletuGroup, new Point(299, 38));

            // Select 'Beograd, SRB' in 'doComboBox' combo box
            uIDoComboBoxComboBox.SelectedItem = this.FormaErrorsPosiljaocParams.UIDoComboBoxComboBoxSelectedItem;

            // Type '9363' in 'distancaTextBox' text box
            uIDistancaTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UIDistancaTextBoxEditText;

            // Type '{Tab}' in 'distancaTextBox' text box
            Keyboard.SendKeys(uIDistancaTextBoxEdit, this.FormaErrorsPosiljaocParams.UIDistancaTextBoxEditSendKeys, ModifierKeys.None);

            // Type '0.125' in 'takseTextBox' text box
            uITakseTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UITakseTextBoxEditText;

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(139, 11));

            // Type 'a' in 'imeTextBox' text box
            uIImeTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UIImeTextBoxEditText2;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(168, 18));

            // Type 'aaa' in 'imeTextBox' text box
            uIImeTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UIImeTextBoxEditText3;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(132, 13));

            // Type 'd' in 'prezimeTextBox' text box
            uIPrezimeTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UIPrezimeTextBoxEditText2;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(141, 17));

            // Click 'prezimeTextBox' window
            Mouse.Click(uIPrezimeTextBoxWindow, new Point(40, 1));

            // Type 'ddd' in 'prezimeTextBox' text box
            uIPrezimeTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UIPrezimeTextBoxEditText3;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(138, 18));

            // Type '2901994176666' in 'JMBGTextBox' text box
            uIJMBGTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UIJMBGTextBoxEditText2;

            // Double-Click 'Rezerviši let' button
            Mouse.DoubleClick(uIRezervišiletButton, new Point(155, 5));

            // Type '2901994175003' in 'JMBGTextBox' text box
            uIJMBGTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UIJMBGTextBoxEditText3;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(135, 19));

            // Type '+38762-282222' in 'telefonTextBox' text box
            uITelefonTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UITelefonTextBoxEditText2;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(139, 27));

            // Type '+38762-282-222' in 'telefonTextBox' text box
            uITelefonTextBoxEdit.Text = this.FormaErrorsPosiljaocParams.UITelefonTextBoxEditText3;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(171, 14));

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(145, 15));
        }
        
        /// <summary>
        /// PosiljaocErrors - Use 'PosiljaocErrorsParams' to pass parameters into this method.
        /// </summary>
        public void PosiljaocErrors()
        {
            #region Variable Declarations
            WinEdit uINameEdit = this.UIDebugWindow.UIItemWindow.UILufthansaFormListItem.UINameEdit;
            WinComboBox uIDOComboBox = this.UIForm1Window.UIOdComboBoxWindow.UIDOComboBox;
            WinComboBox uIDoComboBoxComboBox = this.UIForm1Window.UIDoComboBoxWindow.UIDoComboBoxComboBox;
            WinEdit uIDistancaTextBoxEdit = this.UIForm1Window.UIDistancaTextBoxWindow.UIDistancaTextBoxEdit;
            WinEdit uIPrtljagTextBoxEdit = this.UIForm1Window.UIPrtljagTextBoxWindow.UIPrtljagTextBoxEdit;
            WinEdit uITakseTextBoxEdit = this.UIForm1Window.UITakseTextBoxWindow.UITakseTextBoxEdit;
            WinButton uIIzračunajcijenuletaButton = this.UIForm1Window.UIIzračunajcijenuletaWindow.UIIzračunajcijenuletaButton;
            WinEdit uIImeTextBoxEdit = this.UIForm1Window.UIImeTextBoxWindow.UIImeTextBoxEdit;
            WinButton uIRezervišiletButton = this.UIForm1Window.UIRezervišiletWindow.UIRezervišiletButton;
            WinEdit uIPrezimeTextBoxEdit = this.UIForm1Window.UIPrezimeTextBoxWindow.UIPrezimeTextBoxEdit;
            WinEdit uIJMBGTextBoxEdit = this.UIForm1Window.UIJMBGTextBoxWindow.UIJMBGTextBoxEdit;
            WinEdit uITelefonTextBoxEdit = this.UIForm1Window.UITelefonTextBoxWindow.UITelefonTextBoxEdit;
            WinButton uICloseButton = this.UIForm1Window.UIForm1TitleBar.UICloseButton;
            #endregion

            // Double-Click 'Name' text box
            Mouse.DoubleClick(uINameEdit, new Point(91, 13));

            // Select 'Sarajevo, BiH' in 'Do:' combo box
            uIDOComboBox.SelectedItem = this.PosiljaocErrorsParams.UIDOComboBoxSelectedItem;

            // Select 'Beograd, SRB' in 'doComboBox' combo box
            uIDoComboBoxComboBox.SelectedItem = this.PosiljaocErrorsParams.UIDoComboBoxComboBoxSelectedItem;

            // Type '9363' in 'distancaTextBox' text box
            uIDistancaTextBoxEdit.Text = this.PosiljaocErrorsParams.UIDistancaTextBoxEditText;

            // Type '4' in 'prtljagTextBox' text box
            uIPrtljagTextBoxEdit.Text = this.PosiljaocErrorsParams.UIPrtljagTextBoxEditText;

            // Type '0.125' in 'takseTextBox' text box
            uITakseTextBoxEdit.Text = this.PosiljaocErrorsParams.UITakseTextBoxEditText;

            // Click 'Izračunaj cijenu leta' button
            Mouse.Click(uIIzračunajcijenuletaButton, new Point(87, 19));

            // Type 'a' in 'imeTextBox' text box
            uIImeTextBoxEdit.Text = this.PosiljaocErrorsParams.UIImeTextBoxEditText;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(133, 10));

            // Type 'aaa' in 'imeTextBox' text box
            uIImeTextBoxEdit.Text = this.PosiljaocErrorsParams.UIImeTextBoxEditText1;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(124, 25));

            // Type 'd' in 'prezimeTextBox' text box
            uIPrezimeTextBoxEdit.Text = this.PosiljaocErrorsParams.UIPrezimeTextBoxEditText;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(115, 21));

            // Type 'ddd' in 'prezimeTextBox' text box
            uIPrezimeTextBoxEdit.Text = this.PosiljaocErrorsParams.UIPrezimeTextBoxEditText1;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(158, 10));

            // Type '2901994175000' in 'JMBGTextBox' text box
            uIJMBGTextBoxEdit.Text = this.PosiljaocErrorsParams.UIJMBGTextBoxEditText;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(129, 9));

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(134, 15));

            // Type '2901994175003' in 'JMBGTextBox' text box
            uIJMBGTextBoxEdit.Text = this.PosiljaocErrorsParams.UIJMBGTextBoxEditText1;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(185, 19));

            // Type '+38762-222222' in 'telefonTextBox' text box
            uITelefonTextBoxEdit.Text = this.PosiljaocErrorsParams.UITelefonTextBoxEditText;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(178, 17));

            // Type '+38762-222-222' in 'telefonTextBox' text box
            uITelefonTextBoxEdit.Text = this.PosiljaocErrorsParams.UITelefonTextBoxEditText1;

            // Click 'Rezerviši let' button
            Mouse.Click(uIRezervišiletButton, new Point(164, 21));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(20, 16));
        }
        
        #region Properties
        public virtual IzracunajCijenuLetaParams IzracunajCijenuLetaParams
        {
            get
            {
                if ((this.mIzracunajCijenuLetaParams == null))
                {
                    this.mIzracunajCijenuLetaParams = new IzracunajCijenuLetaParams();
                }
                return this.mIzracunajCijenuLetaParams;
            }
        }
        
        public virtual RezervisiLetParams RezervisiLetParams
        {
            get
            {
                if ((this.mRezervisiLetParams == null))
                {
                    this.mRezervisiLetParams = new RezervisiLetParams();
                }
                return this.mRezervisiLetParams;
            }
        }
        
        public virtual FormaErrorsParams FormaErrorsParams
        {
            get
            {
                if ((this.mFormaErrorsParams == null))
                {
                    this.mFormaErrorsParams = new FormaErrorsParams();
                }
                return this.mFormaErrorsParams;
            }
        }
        
        public virtual FormaErrorsPosiljaocParams FormaErrorsPosiljaocParams
        {
            get
            {
                if ((this.mFormaErrorsPosiljaocParams == null))
                {
                    this.mFormaErrorsPosiljaocParams = new FormaErrorsPosiljaocParams();
                }
                return this.mFormaErrorsPosiljaocParams;
            }
        }
        
        public virtual PosiljaocErrorsParams PosiljaocErrorsParams
        {
            get
            {
                if ((this.mPosiljaocErrorsParams == null))
                {
                    this.mPosiljaocErrorsParams = new PosiljaocErrorsParams();
                }
                return this.mPosiljaocErrorsParams;
            }
        }
        
        public UIDebugWindow UIDebugWindow
        {
            get
            {
                if ((this.mUIDebugWindow == null))
                {
                    this.mUIDebugWindow = new UIDebugWindow();
                }
                return this.mUIDebugWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow1();
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIForm1Window UIForm1Window
        {
            get
            {
                if ((this.mUIForm1Window == null))
                {
                    this.mUIForm1Window = new UIForm1Window();
                }
                return this.mUIForm1Window;
            }
        }
        
        public UIForm1Window1 UIForm1Window1
        {
            get
            {
                if ((this.mUIForm1Window1 == null))
                {
                    this.mUIForm1Window1 = new UIForm1Window1();
                }
                return this.mUIForm1Window1;
            }
        }
        #endregion
        
        #region Fields
        private IzracunajCijenuLetaParams mIzracunajCijenuLetaParams;
        
        private RezervisiLetParams mRezervisiLetParams;
        
        private FormaErrorsParams mFormaErrorsParams;
        
        private FormaErrorsPosiljaocParams mFormaErrorsPosiljaocParams;
        
        private PosiljaocErrorsParams mPosiljaocErrorsParams;
        
        private UIDebugWindow mUIDebugWindow;
        
        private UIItemWindow1 mUIItemWindow;
        
        private UIForm1Window mUIForm1Window;
        
        private UIForm1Window1 mUIForm1Window1;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'IzracunajCijenuLeta'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class IzracunajCijenuLetaParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Sarajevo, BiH' in 'Do:' combo box
        /// </summary>
        public string UIDOComboBoxSelectedItem = "Sarajevo, BiH";
        
        /// <summary>
        /// Select 'Beograd, SRB' in 'doComboBox' combo box
        /// </summary>
        public string UIDoComboBoxComboBoxSelectedItem = "Beograd, SRB";
        
        /// <summary>
        /// Type '9363' in 'distancaTextBox' text box
        /// </summary>
        public string UIDistancaTextBoxEditText = "9363";
        
        /// <summary>
        /// Type '{Tab}' in 'distancaTextBox' text box
        /// </summary>
        public string UIDistancaTextBoxEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '0.125' in 'takseTextBox' text box
        /// </summary>
        public string UITakseTextBoxEditText = "0.125";
        
        /// <summary>
        /// Set position '1' in 'trackBar1' slider
        /// </summary>
        public string UITrackBar1SliderPositionAsString = "1";
        
        /// <summary>
        /// Select 'Sarajevo, BiH' in 'Do:' combo box
        /// </summary>
        public string UIDOComboBoxSelectedItem1 = "Sarajevo, BiH";
        
        /// <summary>
        /// Select 'Beograd, SRB' in 'doComboBox' combo box
        /// </summary>
        public string UIDoComboBoxComboBoxSelectedItem1 = "Beograd, SRB";
        
        /// <summary>
        /// Type '9363' in 'distancaTextBox' text box
        /// </summary>
        public string UIDistancaTextBoxEditText1 = "9363";
        
        /// <summary>
        /// Type '4' in 'prtljagTextBox' text box
        /// </summary>
        public string UIPrtljagTextBoxEditText = "4";
        
        /// <summary>
        /// Type '0.125' in 'takseTextBox' text box
        /// </summary>
        public string UITakseTextBoxEditText1 = "0.125";
        
        /// <summary>
        /// Set position '1' in 'trackBar1' slider
        /// </summary>
        public string UITrackBar1SliderPositionAsString1 = "1";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RezervisiLet'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class RezervisiLetParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Sarajevo, BiH' in 'Do:' combo box
        /// </summary>
        public string UIDOComboBoxSelectedItem = "Sarajevo, BiH";
        
        /// <summary>
        /// Select 'Beograd, SRB' in 'doComboBox' combo box
        /// </summary>
        public string UIDoComboBoxComboBoxSelectedItem = "Beograd, SRB";
        
        /// <summary>
        /// Type '9363' in 'distancaTextBox' text box
        /// </summary>
        public string UIDistancaTextBoxEditText = "9363";
        
        /// <summary>
        /// Type '4' in 'prtljagTextBox' text box
        /// </summary>
        public string UIPrtljagTextBoxEditText = "4";
        
        /// <summary>
        /// Type '0.2' in 'takseTextBox' text box
        /// </summary>
        public string UITakseTextBoxEditText = "0.2";
        
        /// <summary>
        /// Set position '5' in 'trackBar1' slider
        /// </summary>
        public string UITrackBar1SliderPositionAsString = "5";
        
        /// <summary>
        /// Type 'Amela' in 'imeTextBox' text box
        /// </summary>
        public string UIImeTextBoxEditText = "Amela";
        
        /// <summary>
        /// Type 'Spica' in 'prezimeTextBox' text box
        /// </summary>
        public string UIPrezimeTextBoxEditText = "Spica";
        
        /// <summary>
        /// Type '2901994175003' in 'JMBGTextBox' text box
        /// </summary>
        public string UIJMBGTextBoxEditText = "2901994175003";
        
        /// <summary>
        /// Type '+38762-999-999' in 'telefonTextBox' text box
        /// </summary>
        public string UITelefonTextBoxEditText = "+38762-999-999";
        
        /// <summary>
        /// Type 'sdfs' in 'komentarRichTextBox' text box
        /// </summary>
        public string UIKomentarRichTextBoxEditText = "sdfs";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'FormaErrors'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class FormaErrorsParams
    {
        
        #region Fields
        /// <summary>
        /// Type '9363' in 'distancaTextBox' text box
        /// </summary>
        public string UIDistancaTextBoxEditText = "9363";
        
        /// <summary>
        /// Type '4' in 'prtljagTextBox' text box
        /// </summary>
        public string UIPrtljagTextBoxEditText = "4";
        
        /// <summary>
        /// Type '0.125' in 'takseTextBox' text box
        /// </summary>
        public string UITakseTextBoxEditText = "0.125";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'FormaErrorsPosiljaoc'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class FormaErrorsPosiljaocParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'a' in 'imeTextBox' text box
        /// </summary>
        public string UIImeTextBoxEditText = "a";
        
        /// <summary>
        /// Type 'afd' in 'imeTextBox' text box
        /// </summary>
        public string UIImeTextBoxEditText1 = "afd";
        
        /// <summary>
        /// Type 'a' in 'prezimeTextBox' text box
        /// </summary>
        public string UIPrezimeTextBoxEditText = "a";
        
        /// <summary>
        /// Type 'ad' in 'prezimeTextBox' text box
        /// </summary>
        public string UIPrezimeTextBoxEditText1 = "ad";
        
        /// <summary>
        /// Type '2901994176333' in 'JMBGTextBox' text box
        /// </summary>
        public string UIJMBGTextBoxEditText = "2901994176333";
        
        /// <summary>
        /// Type '2901994175003' in 'JMBGTextBox' text box
        /// </summary>
        public string UIJMBGTextBoxEditText1 = "2901994175003";
        
        /// <summary>
        /// Type '+38762-888888' in 'telefonTextBox' text box
        /// </summary>
        public string UITelefonTextBoxEditText = "+38762-888888";
        
        /// <summary>
        /// Type '+38762-888-888' in 'telefonTextBox' text box
        /// </summary>
        public string UITelefonTextBoxEditText1 = "+38762-888-888";
        
        /// <summary>
        /// Select 'Sarajevo, BiH' in 'Do:' combo box
        /// </summary>
        public string UIDOComboBoxSelectedItem = "Sarajevo, BiH";
        
        /// <summary>
        /// Select 'Beograd, SRB' in 'doComboBox' combo box
        /// </summary>
        public string UIDoComboBoxComboBoxSelectedItem = "Beograd, SRB";
        
        /// <summary>
        /// Type '9363' in 'distancaTextBox' text box
        /// </summary>
        public string UIDistancaTextBoxEditText = "9363";
        
        /// <summary>
        /// Type '{Tab}' in 'distancaTextBox' text box
        /// </summary>
        public string UIDistancaTextBoxEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '0.125' in 'takseTextBox' text box
        /// </summary>
        public string UITakseTextBoxEditText = "0.125";
        
        /// <summary>
        /// Type 'a' in 'imeTextBox' text box
        /// </summary>
        public string UIImeTextBoxEditText2 = "a";
        
        /// <summary>
        /// Type 'aaa' in 'imeTextBox' text box
        /// </summary>
        public string UIImeTextBoxEditText3 = "aaa";
        
        /// <summary>
        /// Type 'd' in 'prezimeTextBox' text box
        /// </summary>
        public string UIPrezimeTextBoxEditText2 = "d";
        
        /// <summary>
        /// Type 'ddd' in 'prezimeTextBox' text box
        /// </summary>
        public string UIPrezimeTextBoxEditText3 = "ddd";
        
        /// <summary>
        /// Type '2901994176666' in 'JMBGTextBox' text box
        /// </summary>
        public string UIJMBGTextBoxEditText2 = "2901994176666";
        
        /// <summary>
        /// Type '2901994175003' in 'JMBGTextBox' text box
        /// </summary>
        public string UIJMBGTextBoxEditText3 = "2901994175003";
        
        /// <summary>
        /// Type '+38762-282222' in 'telefonTextBox' text box
        /// </summary>
        public string UITelefonTextBoxEditText2 = "+38762-282222";
        
        /// <summary>
        /// Type '+38762-282-222' in 'telefonTextBox' text box
        /// </summary>
        public string UITelefonTextBoxEditText3 = "+38762-282-222";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'PosiljaocErrors'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class PosiljaocErrorsParams
    {
        
        #region Fields
        /// <summary>
        /// Select 'Sarajevo, BiH' in 'Do:' combo box
        /// </summary>
        public string UIDOComboBoxSelectedItem = "Sarajevo, BiH";
        
        /// <summary>
        /// Select 'Beograd, SRB' in 'doComboBox' combo box
        /// </summary>
        public string UIDoComboBoxComboBoxSelectedItem = "Beograd, SRB";
        
        /// <summary>
        /// Type '9363' in 'distancaTextBox' text box
        /// </summary>
        public string UIDistancaTextBoxEditText = "9363";
        
        /// <summary>
        /// Type '4' in 'prtljagTextBox' text box
        /// </summary>
        public string UIPrtljagTextBoxEditText = "4";
        
        /// <summary>
        /// Type '0.125' in 'takseTextBox' text box
        /// </summary>
        public string UITakseTextBoxEditText = "0.125";
        
        /// <summary>
        /// Type 'a' in 'imeTextBox' text box
        /// </summary>
        public string UIImeTextBoxEditText = "a";
        
        /// <summary>
        /// Type 'aaa' in 'imeTextBox' text box
        /// </summary>
        public string UIImeTextBoxEditText1 = "aaa";
        
        /// <summary>
        /// Type 'd' in 'prezimeTextBox' text box
        /// </summary>
        public string UIPrezimeTextBoxEditText = "d";
        
        /// <summary>
        /// Type 'ddd' in 'prezimeTextBox' text box
        /// </summary>
        public string UIPrezimeTextBoxEditText1 = "ddd";
        
        /// <summary>
        /// Type '2901994175000' in 'JMBGTextBox' text box
        /// </summary>
        public string UIJMBGTextBoxEditText = "2901994175000";
        
        /// <summary>
        /// Type '2901994175003' in 'JMBGTextBox' text box
        /// </summary>
        public string UIJMBGTextBoxEditText1 = "2901994175003";
        
        /// <summary>
        /// Type '+38762-222222' in 'telefonTextBox' text box
        /// </summary>
        public string UITelefonTextBoxEditText = "+38762-222222";
        
        /// <summary>
        /// Type '+38762-222-222' in 'telefonTextBox' text box
        /// </summary>
        public string UITelefonTextBoxEditText1 = "+38762-222-222";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDebugWindow : WinWindow
    {
        
        public UIDebugWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Debug";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Items View";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public UILufthansaFormexeListItem UILufthansaFormexeListItem
        {
            get
            {
                if ((this.mUILufthansaFormexeListItem == null))
                {
                    this.mUILufthansaFormexeListItem = new UILufthansaFormexeListItem(this);
                }
                return this.mUILufthansaFormexeListItem;
            }
        }
        
        public UILufthansaFormListItem UILufthansaFormListItem
        {
            get
            {
                if ((this.mUILufthansaFormListItem == null))
                {
                    this.mUILufthansaFormListItem = new UILufthansaFormListItem(this);
                }
                return this.mUILufthansaFormListItem;
            }
        }
        #endregion
        
        #region Fields
        private UILufthansaFormexeListItem mUILufthansaFormexeListItem;
        
        private UILufthansaFormListItem mUILufthansaFormListItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILufthansaFormexeListItem : WinListItem
    {
        
        public UILufthansaFormexeListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "LufthansaForm.exe";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILufthansaFormListItem : WinListItem
    {
        
        public UILufthansaFormListItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinListItem.PropertyNames.Name] = "LufthansaForm";
            this.WindowTitles.Add("Debug");
            #endregion
        }
        
        #region Properties
        public WinEdit UINameEdit
        {
            get
            {
                if ((this.mUINameEdit == null))
                {
                    this.mUINameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUINameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Name";
                    this.mUINameEdit.WindowTitles.Add("Debug");
                    #endregion
                }
                return this.mUINameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUINameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Flyout window";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "DirectUIHWND";
            #endregion
        }
        
        #region Properties
        public WinClient UIFlyoutwindowClient
        {
            get
            {
                if ((this.mUIFlyoutwindowClient == null))
                {
                    this.mUIFlyoutwindowClient = new WinClient(this);
                    #region Search Criteria
                    this.mUIFlyoutwindowClient.SearchProperties[WinControl.PropertyNames.Name] = "Flyout window";
                    #endregion
                }
                return this.mUIFlyoutwindowClient;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIFlyoutwindowClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIForm1Window : WinWindow
    {
        
        public UIForm1Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Form1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UIOdComboBoxWindow UIOdComboBoxWindow
        {
            get
            {
                if ((this.mUIOdComboBoxWindow == null))
                {
                    this.mUIOdComboBoxWindow = new UIOdComboBoxWindow(this);
                }
                return this.mUIOdComboBoxWindow;
            }
        }
        
        public UIDoComboBoxWindow UIDoComboBoxWindow
        {
            get
            {
                if ((this.mUIDoComboBoxWindow == null))
                {
                    this.mUIDoComboBoxWindow = new UIDoComboBoxWindow(this);
                }
                return this.mUIDoComboBoxWindow;
            }
        }
        
        public UIDistancaTextBoxWindow UIDistancaTextBoxWindow
        {
            get
            {
                if ((this.mUIDistancaTextBoxWindow == null))
                {
                    this.mUIDistancaTextBoxWindow = new UIDistancaTextBoxWindow(this);
                }
                return this.mUIDistancaTextBoxWindow;
            }
        }
        
        public UITakseTextBoxWindow UITakseTextBoxWindow
        {
            get
            {
                if ((this.mUITakseTextBoxWindow == null))
                {
                    this.mUITakseTextBoxWindow = new UITakseTextBoxWindow(this);
                }
                return this.mUITakseTextBoxWindow;
            }
        }
        
        public UITrackBar1Window UITrackBar1Window
        {
            get
            {
                if ((this.mUITrackBar1Window == null))
                {
                    this.mUITrackBar1Window = new UITrackBar1Window(this);
                }
                return this.mUITrackBar1Window;
            }
        }
        
        public UIIzračunajcijenuletaWindow UIIzračunajcijenuletaWindow
        {
            get
            {
                if ((this.mUIIzračunajcijenuletaWindow == null))
                {
                    this.mUIIzračunajcijenuletaWindow = new UIIzračunajcijenuletaWindow(this);
                }
                return this.mUIIzračunajcijenuletaWindow;
            }
        }
        
        public UIForm1TitleBar UIForm1TitleBar
        {
            get
            {
                if ((this.mUIForm1TitleBar == null))
                {
                    this.mUIForm1TitleBar = new UIForm1TitleBar(this);
                }
                return this.mUIForm1TitleBar;
            }
        }
        
        public UIPodacioletuWindow UIPodacioletuWindow
        {
            get
            {
                if ((this.mUIPodacioletuWindow == null))
                {
                    this.mUIPodacioletuWindow = new UIPodacioletuWindow(this);
                }
                return this.mUIPodacioletuWindow;
            }
        }
        
        public UIPrtljagTextBoxWindow UIPrtljagTextBoxWindow
        {
            get
            {
                if ((this.mUIPrtljagTextBoxWindow == null))
                {
                    this.mUIPrtljagTextBoxWindow = new UIPrtljagTextBoxWindow(this);
                }
                return this.mUIPrtljagTextBoxWindow;
            }
        }
        
        public UIImeTextBoxWindow UIImeTextBoxWindow
        {
            get
            {
                if ((this.mUIImeTextBoxWindow == null))
                {
                    this.mUIImeTextBoxWindow = new UIImeTextBoxWindow(this);
                }
                return this.mUIImeTextBoxWindow;
            }
        }
        
        public UIPrezimeTextBoxWindow UIPrezimeTextBoxWindow
        {
            get
            {
                if ((this.mUIPrezimeTextBoxWindow == null))
                {
                    this.mUIPrezimeTextBoxWindow = new UIPrezimeTextBoxWindow(this);
                }
                return this.mUIPrezimeTextBoxWindow;
            }
        }
        
        public UIJMBGTextBoxWindow UIJMBGTextBoxWindow
        {
            get
            {
                if ((this.mUIJMBGTextBoxWindow == null))
                {
                    this.mUIJMBGTextBoxWindow = new UIJMBGTextBoxWindow(this);
                }
                return this.mUIJMBGTextBoxWindow;
            }
        }
        
        public UITelefonTextBoxWindow UITelefonTextBoxWindow
        {
            get
            {
                if ((this.mUITelefonTextBoxWindow == null))
                {
                    this.mUITelefonTextBoxWindow = new UITelefonTextBoxWindow(this);
                }
                return this.mUITelefonTextBoxWindow;
            }
        }
        
        public UIKomentarRichTextBoxWindow UIKomentarRichTextBoxWindow
        {
            get
            {
                if ((this.mUIKomentarRichTextBoxWindow == null))
                {
                    this.mUIKomentarRichTextBoxWindow = new UIKomentarRichTextBoxWindow(this);
                }
                return this.mUIKomentarRichTextBoxWindow;
            }
        }
        
        public UIRezervišiletWindow UIRezervišiletWindow
        {
            get
            {
                if ((this.mUIRezervišiletWindow == null))
                {
                    this.mUIRezervišiletWindow = new UIRezervišiletWindow(this);
                }
                return this.mUIRezervišiletWindow;
            }
        }
        
        public UIDataGridView1Window UIDataGridView1Window
        {
            get
            {
                if ((this.mUIDataGridView1Window == null))
                {
                    this.mUIDataGridView1Window = new UIDataGridView1Window(this);
                }
                return this.mUIDataGridView1Window;
            }
        }
        
        public UIIzbrišiuneseniletWindow UIIzbrišiuneseniletWindow
        {
            get
            {
                if ((this.mUIIzbrišiuneseniletWindow == null))
                {
                    this.mUIIzbrišiuneseniletWindow = new UIIzbrišiuneseniletWindow(this);
                }
                return this.mUIIzbrišiuneseniletWindow;
            }
        }
        
        public UIPodacioletuGroup UIPodacioletuGroup
        {
            get
            {
                if ((this.mUIPodacioletuGroup == null))
                {
                    this.mUIPodacioletuGroup = new UIPodacioletuGroup(this);
                }
                return this.mUIPodacioletuGroup;
            }
        }
        
        public UILičnipodaciGroup UILičnipodaciGroup
        {
            get
            {
                if ((this.mUILičnipodaciGroup == null))
                {
                    this.mUILičnipodaciGroup = new UILičnipodaciGroup(this);
                }
                return this.mUILičnipodaciGroup;
            }
        }
        
        public UILičnipodaciWindow UILičnipodaciWindow
        {
            get
            {
                if ((this.mUILičnipodaciWindow == null))
                {
                    this.mUILičnipodaciWindow = new UILičnipodaciWindow(this);
                }
                return this.mUILičnipodaciWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIOdComboBoxWindow mUIOdComboBoxWindow;
        
        private UIDoComboBoxWindow mUIDoComboBoxWindow;
        
        private UIDistancaTextBoxWindow mUIDistancaTextBoxWindow;
        
        private UITakseTextBoxWindow mUITakseTextBoxWindow;
        
        private UITrackBar1Window mUITrackBar1Window;
        
        private UIIzračunajcijenuletaWindow mUIIzračunajcijenuletaWindow;
        
        private UIForm1TitleBar mUIForm1TitleBar;
        
        private UIPodacioletuWindow mUIPodacioletuWindow;
        
        private UIPrtljagTextBoxWindow mUIPrtljagTextBoxWindow;
        
        private UIImeTextBoxWindow mUIImeTextBoxWindow;
        
        private UIPrezimeTextBoxWindow mUIPrezimeTextBoxWindow;
        
        private UIJMBGTextBoxWindow mUIJMBGTextBoxWindow;
        
        private UITelefonTextBoxWindow mUITelefonTextBoxWindow;
        
        private UIKomentarRichTextBoxWindow mUIKomentarRichTextBoxWindow;
        
        private UIRezervišiletWindow mUIRezervišiletWindow;
        
        private UIDataGridView1Window mUIDataGridView1Window;
        
        private UIIzbrišiuneseniletWindow mUIIzbrišiuneseniletWindow;
        
        private UIPodacioletuGroup mUIPodacioletuGroup;
        
        private UILičnipodaciGroup mUILičnipodaciGroup;
        
        private UILičnipodaciWindow mUILičnipodaciWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIOdComboBoxWindow : WinWindow
    {
        
        public UIOdComboBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "odComboBox";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIDOComboBox
        {
            get
            {
                if ((this.mUIDOComboBox == null))
                {
                    this.mUIDOComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIDOComboBox.SearchProperties[WinComboBox.PropertyNames.Name] = "Do:";
                    this.mUIDOComboBox.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIDOComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIDOComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDoComboBoxWindow : WinWindow
    {
        
        public UIDoComboBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "doComboBox";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIDoComboBoxComboBox
        {
            get
            {
                if ((this.mUIDoComboBoxComboBox == null))
                {
                    this.mUIDoComboBoxComboBox = new WinComboBox(this);
                    #region Search Criteria
                    this.mUIDoComboBoxComboBox.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIDoComboBoxComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIDoComboBoxComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDistancaTextBoxWindow : WinWindow
    {
        
        public UIDistancaTextBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "distancaTextBox";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UIDistancaTextBoxEdit
        {
            get
            {
                if ((this.mUIDistancaTextBoxEdit == null))
                {
                    this.mUIDistancaTextBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIDistancaTextBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Distanca:";
                    this.mUIDistancaTextBoxEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIDistancaTextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIDistancaTextBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITakseTextBoxWindow : WinWindow
    {
        
        public UITakseTextBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "takseTextBox";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITakseTextBoxEdit
        {
            get
            {
                if ((this.mUITakseTextBoxEdit == null))
                {
                    this.mUITakseTextBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITakseTextBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Takse:";
                    this.mUITakseTextBoxEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITakseTextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITakseTextBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITrackBar1Window : WinWindow
    {
        
        public UITrackBar1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "trackBar1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinSlider UITrackBar1Slider
        {
            get
            {
                if ((this.mUITrackBar1Slider == null))
                {
                    this.mUITrackBar1Slider = new WinSlider(this);
                    #region Search Criteria
                    this.mUITrackBar1Slider.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITrackBar1Slider;
            }
        }
        #endregion
        
        #region Fields
        private WinSlider mUITrackBar1Slider;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIzračunajcijenuletaWindow : WinWindow
    {
        
        public UIIzračunajcijenuletaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "izracunajCijenuLetaButton";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIIzračunajcijenuletaButton
        {
            get
            {
                if ((this.mUIIzračunajcijenuletaButton == null))
                {
                    this.mUIIzračunajcijenuletaButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIIzračunajcijenuletaButton.SearchProperties[WinButton.PropertyNames.Name] = "Izračunaj cijenu leta";
                    this.mUIIzračunajcijenuletaButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIIzračunajcijenuletaButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIIzračunajcijenuletaButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIForm1TitleBar : WinTitleBar
    {
        
        public UIForm1TitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPodacioletuWindow : WinWindow
    {
        
        public UIPodacioletuWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "podaciOLetuGroupBox";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinGroup UIPodacioletuGroup
        {
            get
            {
                if ((this.mUIPodacioletuGroup == null))
                {
                    this.mUIPodacioletuGroup = new WinGroup(this);
                    #region Search Criteria
                    this.mUIPodacioletuGroup.SearchProperties[WinControl.PropertyNames.Name] = "Podaci o letu";
                    this.mUIPodacioletuGroup.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIPodacioletuGroup;
            }
        }
        #endregion
        
        #region Fields
        private WinGroup mUIPodacioletuGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPrtljagTextBoxWindow : WinWindow
    {
        
        public UIPrtljagTextBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "prtljagTextBox";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UIPrtljagTextBoxEdit
        {
            get
            {
                if ((this.mUIPrtljagTextBoxEdit == null))
                {
                    this.mUIPrtljagTextBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIPrtljagTextBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Prtljag:";
                    this.mUIPrtljagTextBoxEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIPrtljagTextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIPrtljagTextBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIImeTextBoxWindow : WinWindow
    {
        
        public UIImeTextBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "imeTextBox";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UIImeTextBoxEdit
        {
            get
            {
                if ((this.mUIImeTextBoxEdit == null))
                {
                    this.mUIImeTextBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIImeTextBoxEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIImeTextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIImeTextBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPrezimeTextBoxWindow : WinWindow
    {
        
        public UIPrezimeTextBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "prezimeTextBox";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UIPrezimeTextBoxEdit
        {
            get
            {
                if ((this.mUIPrezimeTextBoxEdit == null))
                {
                    this.mUIPrezimeTextBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIPrezimeTextBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Telefon:";
                    this.mUIPrezimeTextBoxEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIPrezimeTextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIPrezimeTextBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIJMBGTextBoxWindow : WinWindow
    {
        
        public UIJMBGTextBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "JMBGTextBox";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UIJMBGTextBoxEdit
        {
            get
            {
                if ((this.mUIJMBGTextBoxEdit == null))
                {
                    this.mUIJMBGTextBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIJMBGTextBoxEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIJMBGTextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIJMBGTextBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITelefonTextBoxWindow : WinWindow
    {
        
        public UITelefonTextBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "telefonTextBox";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITelefonTextBoxEdit
        {
            get
            {
                if ((this.mUITelefonTextBoxEdit == null))
                {
                    this.mUITelefonTextBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITelefonTextBoxEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITelefonTextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITelefonTextBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIKomentarRichTextBoxWindow : WinWindow
    {
        
        public UIKomentarRichTextBoxWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "komentarRichTextBox";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UIKomentarRichTextBoxEdit
        {
            get
            {
                if ((this.mUIKomentarRichTextBoxEdit == null))
                {
                    this.mUIKomentarRichTextBoxEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUIKomentarRichTextBoxEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Komentar:";
                    this.mUIKomentarRichTextBoxEdit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIKomentarRichTextBoxEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIKomentarRichTextBoxEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRezervišiletWindow : WinWindow
    {
        
        public UIRezervišiletWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "rezervisiLetButton";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIRezervišiletButton
        {
            get
            {
                if ((this.mUIRezervišiletButton == null))
                {
                    this.mUIRezervišiletButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIRezervišiletButton.SearchProperties[WinButton.PropertyNames.Name] = "Rezerviši let";
                    this.mUIRezervišiletButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIRezervišiletButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIRezervišiletButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDataGridView1Window : WinWindow
    {
        
        public UIDataGridView1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "dataGridView1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UIDataGridViewTable UIDataGridViewTable
        {
            get
            {
                if ((this.mUIDataGridViewTable == null))
                {
                    this.mUIDataGridViewTable = new UIDataGridViewTable(this);
                }
                return this.mUIDataGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridViewTable mUIDataGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDataGridViewTable : WinTable
    {
        
        public UIDataGridViewTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTable.PropertyNames.Name] = "DataGridView";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UIRow2Row UIRow2Row
        {
            get
            {
                if ((this.mUIRow2Row == null))
                {
                    this.mUIRow2Row = new UIRow2Row(this);
                }
                return this.mUIRow2Row;
            }
        }
        
        public UIRow2Row1 UIRow2Row1
        {
            get
            {
                if ((this.mUIRow2Row1 == null))
                {
                    this.mUIRow2Row1 = new UIRow2Row1(this);
                }
                return this.mUIRow2Row1;
            }
        }
        #endregion
        
        #region Fields
        private UIRow2Row mUIRow2Row;
        
        private UIRow2Row1 mUIRow2Row1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRow2Row : WinRow
    {
        
        public UIRow2Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinRow.PropertyNames.Value, ";9363;4;0.2;5;Amela Spica;2901994175003;+38762-999-999;sdfs", PropertyExpressionOperator.Contains));
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinCell UIItem9363Cell
        {
            get
            {
                if ((this.mUIItem9363Cell == null))
                {
                    this.mUIItem9363Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem9363Cell.SearchProperties[WinCell.PropertyNames.Value] = "9363";
                    this.mUIItem9363Cell.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItem9363Cell;
            }
        }
        
        public WinRowHeader UIItemRowHeader
        {
            get
            {
                if ((this.mUIItemRowHeader == null))
                {
                    this.mUIItemRowHeader = new WinRowHeader(this);
                    #region Search Criteria
                    this.mUIItemRowHeader.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItemRowHeader;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIItem9363Cell;
        
        private WinRowHeader mUIItemRowHeader;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIRow2Row1 : WinRow
    {
        
        public UIRow2Row1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinRow.PropertyNames.Value, ";9363;4;0.125;0;aaa ddd;2901994175003;+38762-282-222;(null)", PropertyExpressionOperator.Contains));
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinRowHeader UIItemRowHeader
        {
            get
            {
                if ((this.mUIItemRowHeader == null))
                {
                    this.mUIItemRowHeader = new WinRowHeader(this);
                    #region Search Criteria
                    this.mUIItemRowHeader.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItemRowHeader;
            }
        }
        #endregion
        
        #region Fields
        private WinRowHeader mUIItemRowHeader;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIIzbrišiuneseniletWindow : WinWindow
    {
        
        public UIIzbrišiuneseniletWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "izbrisiUneseniLetButton";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIIzbrišiuneseniletButton
        {
            get
            {
                if ((this.mUIIzbrišiuneseniletButton == null))
                {
                    this.mUIIzbrišiuneseniletButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIIzbrišiuneseniletButton.SearchProperties[WinButton.PropertyNames.Name] = "Izbriši uneseni let";
                    this.mUIIzbrišiuneseniletButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIIzbrišiuneseniletButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIIzbrišiuneseniletButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPodacioletuGroup : WinGroup
    {
        
        public UIPodacioletuGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Podaci o letu";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinWindow UIPrtljagTextBoxWindow
        {
            get
            {
                if ((this.mUIPrtljagTextBoxWindow == null))
                {
                    this.mUIPrtljagTextBoxWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIPrtljagTextBoxWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Prtljag:";
                    this.mUIPrtljagTextBoxWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUIPrtljagTextBoxWindow.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIPrtljagTextBoxWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIPrtljagTextBoxWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILičnipodaciGroup : WinGroup
    {
        
        public UILičnipodaciGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Lični podaci";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinWindow UIImeTextBoxWindow
        {
            get
            {
                if ((this.mUIImeTextBoxWindow == null))
                {
                    this.mUIImeTextBoxWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIImeTextBoxWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUIImeTextBoxWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "4";
                    this.mUIImeTextBoxWindow.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIImeTextBoxWindow;
            }
        }
        
        public WinWindow UIJMBGTextBoxWindow
        {
            get
            {
                if ((this.mUIJMBGTextBoxWindow == null))
                {
                    this.mUIJMBGTextBoxWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIJMBGTextBoxWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUIJMBGTextBoxWindow.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
                    this.mUIJMBGTextBoxWindow.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIJMBGTextBoxWindow;
            }
        }
        
        public WinWindow UIPrezimeTextBoxWindow
        {
            get
            {
                if ((this.mUIPrezimeTextBoxWindow == null))
                {
                    this.mUIPrezimeTextBoxWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIPrezimeTextBoxWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Telefon:";
                    this.mUIPrezimeTextBoxWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUIPrezimeTextBoxWindow.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIPrezimeTextBoxWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIImeTextBoxWindow;
        
        private WinWindow mUIJMBGTextBoxWindow;
        
        private WinWindow mUIPrezimeTextBoxWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UILičnipodaciWindow : WinWindow
    {
        
        public UILičnipodaciWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "licniPodaciGroupBox";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinGroup UILičnipodaciGroup
        {
            get
            {
                if ((this.mUILičnipodaciGroup == null))
                {
                    this.mUILičnipodaciGroup = new WinGroup(this);
                    #region Search Criteria
                    this.mUILičnipodaciGroup.SearchProperties[WinControl.PropertyNames.Name] = "Lični podaci";
                    this.mUILičnipodaciGroup.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUILičnipodaciGroup;
            }
        }
        #endregion
        
        #region Fields
        private WinGroup mUILičnipodaciGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIForm1Window1 : WinWindow
    {
        
        public UIForm1Window1()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Form1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.FilterProperties[WinWindow.PropertyNames.OrderOfInvocation] = "2";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UIForm1Client UIForm1Client
        {
            get
            {
                if ((this.mUIForm1Client == null))
                {
                    this.mUIForm1Client = new UIForm1Client(this);
                }
                return this.mUIForm1Client;
            }
        }
        #endregion
        
        #region Fields
        private UIForm1Client mUIForm1Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIForm1Client : WinClient
    {
        
        public UIForm1Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Form1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIQuitButton
        {
            get
            {
                if ((this.mUIQuitButton == null))
                {
                    this.mUIQuitButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIQuitButton.SearchProperties[WinButton.PropertyNames.Name] = "Quit";
                    this.mUIQuitButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIQuitButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIQuitButton;
        #endregion
    }
}
